package javasabr.mqtt.model;

public interface MqttProperties {

  QoS MAXIMUM_QOS_DEFAULT = QoS.EXACTLY_ONCE;

  int MAXIMUM_PROTOCOL_MESSAGE_SIZE = 256 * 1024 * 1024;
  int MAXIMUM_PACKET_ID = 0xFFFF;

  long SESSION_EXPIRY_INTERVAL_DISABLED = 0;
  long SESSION_EXPIRY_INTERVAL_DEFAULT = 120;
  long SESSION_EXPIRY_INTERVAL_MIN = 0;
  long SESSION_EXPIRY_INTERVAL_INFINITY = 0xFFFFFFFFL;
  long SESSION_EXPIRY_INTERVAL_UNDEFINED = -1;

  int RECEIVE_MAXIMUM_PUBLISHES_UNDEFINED = -1;
  int RECEIVE_MAXIMUM_PUBLISHES_MIN = 1;
  int RECEIVE_MAXIMUM_PUBLISHES_DEFAULT = 10;
  int RECEIVE_MAXIMUM_PUBLISHES_MAX = 0xFFFF;

  int MAXIMUM_MESSAGE_SIZE_UNDEFINED = -1;
  int MAXIMUM_MESSAGE_SIZE_DEFAULT = 3074;
  int MAXIMUM_MESSAGE_SIZE_MIN = 128;
  int MAXIMUM_MESSAGE_SIZE_MAX = MAXIMUM_PROTOCOL_MESSAGE_SIZE;

  int MAXIMUM_STRING_LENGTH = 1024;
  int MAXIMUM_BINARY_SIZE = 2048;
  int MAXIMUM_TOPIC_LEVELS = 10;

  long MESSAGE_EXPIRY_INTERVAL_IS_NOT_SET = -1;
  long MESSAGE_EXPIRY_INTERVAL_INFINITY = 0;
  long MESSAGE_EXPIRY_INTERVAL_MIN = 0;

  int TOPIC_ALIAS_MAXIMUM_UNDEFINED = -1;
  int TOPIC_ALIAS_MAXIMUM_DISABLED = 0;

  int SERVER_KEEP_ALIVE_UNDEFINED = -1;
  int SERVER_KEEP_ALIVE_DISABLED = 0;
  int SERVER_KEEP_ALIVE_DEFAULT = 0;
  int SERVER_KEEP_ALIVE_MIN = 0;
  int SERVER_KEEP_ALIVE_MAX = 0xFFFF;

  int TOPIC_ALIAS_MIN = 1;
  int TOPIC_ALIAS_DEFAULT = 10;
  int TOPIC_ALIAS_MAX = 0xFFFF;
  int TOPIC_ALIAS_NOT_SET = Integer.MIN_VALUE;
  int TOPIC_ALIAS_INVALID = 0;

  int SUBSCRIPTION_ID_IS_NOT_SET = 0;
  int MESSAGE_ID_IS_NOT_SET = 0;

  boolean SESSIONS_ENABLED_DEFAULT = true;
  boolean KEEP_ALIVE_ENABLED_DEFAULT = false;
  boolean RETAIN_AVAILABLE_DEFAULT = false;
  boolean WILDCARD_SUBSCRIPTION_AVAILABLE_DEFAULT = false;
  boolean SHARED_SUBSCRIPTION_AVAILABLE_DEFAULT = false;
  boolean SUBSCRIPTION_IDENTIFIER_AVAILABLE_DEFAULT = true;

  int PACKET_ID_FOR_QOS_0 = 0;
}
