package javasabr.mqtt.model;

import java.time.Duration;

public interface MqttProperties {

  QoS MAXIMUM_QOS_DEFAULT = QoS.EXACTLY_ONCE;

  int MAXIMUM_PROTOCOL_MESSAGE_SIZE = 256 * 1024 * 1024;
  int MAXIMUM_PACKET_ID = 0xFFFF;

  long SESSION_EXPIRY_INTERVAL_DISABLED = 0;
  long SESSION_EXPIRY_INTERVAL_MIN = 0;
  long SESSION_EXPIRY_INTERVAL_INFINITY = 0xFFFFFFFFL;
  long SESSION_EXPIRY_INTERVAL_IS_NOT_SET = -1;

  Duration SESSION_EXPIRY_DURATION_INFINITY = Duration.ofSeconds(0xFFFFFFFFL);
  Duration SESSION_EXPIRY_DURATION_DISABLED = Duration.ZERO;
  
  int RECEIVE_MAXIMUM_PUBLISHES_IS_NOT_SET = 0;
  int RECEIVE_MAXIMUM_PUBLISHES_MIN = 1;
  int RECEIVE_MAXIMUM_PUBLISHES_MAX = 0xFFFF;
  int RECEIVE_MAXIMUM_PUBLISHES_DEFAULT = RECEIVE_MAXIMUM_PUBLISHES_MAX;

  int MAXIMUM_MESSAGE_SIZE_IS_NOT_SET = -1;
  int MAXIMUM_MESSAGE_SIZE_DEFAULT = 3074;
  int MAXIMUM_MESSAGE_SIZE_MIN = 64;
  int MAXIMUM_MESSAGE_SIZE_MAX = MAXIMUM_PROTOCOL_MESSAGE_SIZE;

  int MAXIMUM_STRING_LENGTH = 1024;
  int MAXIMUM_BINARY_SIZE = 2048;
  int MAXIMUM_TOPIC_LEVELS = 10;

  long MESSAGE_EXPIRY_INTERVAL_IS_NOT_SET = -1;
  long MESSAGE_EXPIRY_INTERVAL_INFINITY = 0;
  long MESSAGE_EXPIRY_INTERVAL_MIN = 0;

  int TOPIC_ALIAS_MAXIMUM_IS_NOT_SET = 0;
  int TOPIC_ALIAS_MAXIMUM_DISABLED = 0;

  int SERVER_KEEP_ALIVE_IS_NOT_SET = -1;
  int SERVER_KEEP_ALIVE_DISABLED = 0;
  int SERVER_KEEP_ALIVE_DEFAULT = 0;
  int SERVER_KEEP_ALIVE_MIN = 0;
  int SERVER_KEEP_ALIVE_MAX = 0xFFFF;

  int TOPIC_ALIAS_MIN = 1;
  int TOPIC_ALIAS_MAX_DEFAULT = 10;
  int TOPIC_ALIAS_MAX = 0xFFFF;
  int TOPIC_ALIAS_NOT_SET = Integer.MIN_VALUE;
  int TOPIC_ALIAS_INVALID = 0;

  int SUBSCRIPTION_ID_IS_NOT_SET = 0;
  int SUBSCRIPTION_ID_MIN = 1;
  int SUBSCRIPTION_ID_MAX = 268_435_455;

  int MESSAGE_ID_IS_NOT_SET = 0;

  boolean RETAIN_AVAILABLE_DEFAULT = true;
  int RETAIN_AVAILABLE_IS_NOT_SET = -1;

  boolean WILDCARD_SUBSCRIPTION_AVAILABLE_DEFAULT = true;
  int WILDCARD_SUBSCRIPTION_AVAILABLE_IS_NOT_SET = -1;

  boolean SUBSCRIPTION_IDENTIFIER_AVAILABLE_DEFAULT = true;
  int SUBSCRIPTION_IDENTIFIER_AVAILABLE_IS_NOT_SET = -1;

  boolean SHARED_SUBSCRIPTION_AVAILABLE_DEFAULT = true;
  int SHARED_SUBSCRIPTION_AVAILABLE_IS_NOT_SET = -1;

  boolean SESSIONS_ENABLED_DEFAULT = true;
  boolean KEEP_ALIVE_ENABLED_DEFAULT = false;
}
