plugins {
  id("java-library")
  id("configure-java")
  id("groovy")
  id("org.springframework.boot")
}

description = "Standard configuration of standalone version of MQTT Broker"

dependencies {
  implementation projects.coreService
  implementation projects.aclService
  implementation projects.aclGroovyDsl
  implementation projects.authenticationService
  implementation libs.rlib.logger.slf4j
  implementation libs.springboot.starter.core
  implementation libs.springboot.starter.log4j2

  testImplementation projects.testSupport
  testImplementation testFixtures(projects.network)
  testImplementation projects.credentialsSourceFile
  testImplementation projects.authenticationProviderBasic
}

tasks.withType(GroovyCompile).configureEach {
  options.forkOptions.jvmArgs += "--enable-preview"
}

configurations.each {
  it.exclude group: "org.slf4j", module: "slf4j-log4j12"
  it.exclude group: "org.springframework.boot", module: "spring-boot-starter-logging"
}

bootRun {
  mainClass = "javasabr.mqtt.broker.application.MqttBrokerApplication"
  jvmArgs += "--enable-preview"
}

bootJar {
  mainClass = "javasabr.mqtt.broker.application.MqttBrokerApplication"
}
