plugins {
  id("java-library")
  id("configure-java")
  id("groovy")
  id("org.springframework.boot")
}

description = "Standard configuration of standalone version of MQTT Broker"

dependencies {
  implementation projects.coreService
  implementation projects.aclService
  implementation projects.aclGroovyDsl
  implementation projects.authenticationService
  implementation libs.springboot.starter.core

  testImplementation projects.testSupport
  testImplementation testFixtures(projects.network)
  testImplementation projects.credentialsSourceFile
  testImplementation projects.authenticationProviderBasic
}

tasks.withType(GroovyCompile).configureEach {
  options.forkOptions.jvmArgs += "--enable-preview"
  groovyOptions.parameters = true
}

bootRun {
  mainClass = "javasabr.mqtt.broker.application.MqttBrokerApplication"
  jvmArgs += "--enable-preview"
}

bootJar {
  mainClass = "javasabr.mqtt.broker.application.MqttBrokerApplication"
}
