buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "org.springframework.boot:spring-boot-gradle-plugin:4.0.2"
  }
}

repositories {
  maven {
    url  "https://gitlab.com/api/v4/projects/37512056/packages/maven"
  }
}

rootProject.version = "0.0.1"
group = "javasabr.mqtt"

subprojects {
  repositories {
    mavenCentral()
    mavenLocal()
    maven {
      url  "https://gitlab.com/api/v4/projects/37512056/packages/maven"
    }
  }
}

tasks.register("buildSingleArtifact", GradleBuild) {
  group = "build"
  description = "Build all modules -> Build result artifact"
  tasks = ['build', 'bootJar']
}

tasks.register("buildSingleArtifactWithoutTests", GradleBuild) {
  group = "build"
  description = "Build all modules without tests -> Build result artifact"
  tasks = ['classes', 'bootJar']
}

configurations.each {
  it.exclude group: "org.slf4j", module: "slf4j-log4j12"
  it.exclude group: "org.springframework.boot", module: "spring-boot-starter-logging"
}

wrapper {
  gradleVersion = '9.1.0'
  distributionType = Wrapper.DistributionType.ALL
}
