enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

rootProject.name = 'MQTT-Broker'

include(":base")
include(":model")
include(":network")
include(":core-service")
include(":application")
include(":embedded")
include(":test-support")
include(":test-coverage")
include(":acl-groovy-dsl")
include(":acl-engine")
include(":acl-service")
include(":authentication-api")
include(":authentication-service")
include(":auth-provider-basic")
include(":credentials-source-file")
include(":credentials-source-db")
