plugins {
  id("java-library")
  id("groovy")
}

description = "Provide all necessary dependencies for writing tests"

dependencies {
  api libs.rlib.logger.impl
  api libs.hivemq.mqtt.client
  api libs.moquette.broker
  api libs.spring.test
  api libs.spock.core
  api libs.spock.spring
  api libs.groovy.all
  api libs.byte.buddy.dep
  api libs.objenesis
  api libs.project.reactor.core
}
