plugins {
  id("java-library")
  id("configure-java")
  id("groovy")
}

description = "Provides interfaces and minimal implementation of all required services for MQTT Broker"

dependencies {
  api projects.network
  api projects.aclEngine
  api projects.authenticationApi

  testImplementation projects.testSupport
  testImplementation testFixtures(projects.network)
  testImplementation testFixtures(projects.model)
}
