package com.ss.mqtt.broker.model;

public interface MqttPropertyConstants {

    QoS MAXIMUM_QOS_DEFAULT = QoS.EXACTLY_ONCE_DELIVERY;

    int MAXIMUM_PROTOCOL_PACKET_SIZE = 256 * 1024 * 1024;

    long SESSION_EXPIRY_INTERVAL_DEFAULT = 0;
    long SESSION_EXPIRY_INTERVAL_MIN = 0;
    long SESSION_EXPIRY_INTERVAL_INFINITY = 0xFFFFFFFFL;
    long SESSION_EXPIRY_INTERVAL_UNDEFINED = -1;

    int RECEIVE_MAXIMUM_DEFAULT = 0xFFFF;
    int RECEIVE_MAXIMUM_MIN = 1;
    int RECEIVE_MAXIMUM_MAX = RECEIVE_MAXIMUM_DEFAULT;

    int MAXIMUM_PACKET_SIZE_DEFAULT = MAXIMUM_PROTOCOL_PACKET_SIZE;
    int MAXIMUM_PACKET_SIZE_MIN = 1;
    int MAXIMUM_PACKET_SIZE_MAX = MAXIMUM_PROTOCOL_PACKET_SIZE;

    boolean PAYLOAD_FORMAT_INDICATOR_DEFAULT = false;

    long MESSAGE_EXPIRY_INTERVAL_DEFAULT = 0;

    int TOPIC_ALIAS_MAXIMUM_DEFAULT = 0;

    int SERVER_KEEP_ALIVE_UNDEFINED = -1;
    int SERVER_KEEP_ALIVE_MIN = 0;
    int SERVER_KEEP_ALIVE_MAX = 0xFFFF;

    int TOPIC_ALIAS_DEFAULT = 0;
    int TOPIC_ALIAS_MIN = 0;
    int TOPIC_ALIAS_MAX = 0xFFFF;

    int SUBSCRIPTION_ID_NOT_DEFINED = 0;

    boolean RETAIN_AVAILABLE_DEFAULT = true;
    boolean WILDCARD_SUBSCRIPTION_AVAILABLE_DEFAULT = true;
    boolean SHARED_SUBSCRIPTION_AVAILABLE_DEFAULT = true;
    boolean SUBSCRIPTION_IDENTIFIER_AVAILABLE = true;
}
