[versions]
# https://gitlab.com/JavaSaBr/maven-repo/-/packages
rlib = "10.0.alpha11"
# https://mvnrepository.com/artifact/org.projectlombok/lombok
lombok = "1.18.38"
# https://mvnrepository.com/artifact/org.jspecify/jspecify
jspecify = "1.0.0"
# https://mvnrepository.com/artifact/org.testcontainers/testcontainers
testcontainers = "2.0.3"
# https://mvnrepository.com/artifact/io.projectreactor/reactor-core
project-reactor = "3.7.8"
# https://mvnrepository.com/artifact/io.r2dbc/r2dbc-spi
r2dbc = "1.0.0.RELEASE"
# https://mvnrepository.com/artifact/io.r2dbc/r2dbc-pool
r2dbc-pool="1.0.2.RELEASE"
# https://mvnrepository.com/artifact/org.postgresql/r2dbc-postgresql
r2dbc-postgresql="1.1.1.RELEASE"
# https://mvnrepository.com/artifact/org.postgresql/postgresql
jdbc-postgres="42.7.8"
# https://mvnrepository.com/artifact/org.flywaydb/flyway-core
flyway="11.19.0"
# https://mvnrepository.com/artifact/org.spockframework/spock-core
spock = "2.4-M6-groovy-4.0"
# https://mvnrepository.com/artifact/org.apache.groovy/groovy-all
groovy = "4.0.28"
# https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-web
springboot = '4.0.2'
# https://mvnrepository.com/artifact/org.springframework/spring-core
spring = '7.0.3'
# https://mvnrepository.com/artifact/org.assertj/assertj-core
assertj = '3.27.7'
# https://mvnrepository.com/artifact/net.bytebuddy/byte-buddy
byte-buddy = "1.17.6"
# https://mvnrepository.com/artifact/org.objenesis/objenesis
objenesis = "3.4"
# https://mvnrepository.com/artifact/com.hivemq/hivemq-mqtt-client
hivemq-mqtt-client = "1.3.10"
# https://mvnrepository.com/artifact/io.moquette/moquette-broker
moquette-broker = "0.17"
# https://mvnrepository.com/artifact/tools.jackson.core/jackson-core
jackson = "3.0.1"
# https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-core
legacy-jackson = "2.21.1"
# https://mvnrepository.com/artifact/io.netty/netty-handler
netty = "4.2.10.Final"

[libraries]
rlib-network = { module = "javasabr.rlib:rlib-network", version.ref = "rlib" }
rlib-logger-api = { module = "javasabr.rlib:rlib-logger-api", version.ref = "rlib" }
rlib-logger-slf4j = { module = "javasabr.rlib:rlib-logger-slf4j", version.ref = "rlib" }
rlib-logger-impl = { module = "javasabr.rlib:rlib-logger-impl", version.ref = "rlib" }
rlib-collections = { module = "javasabr.rlib:rlib-collections", version.ref = "rlib" }
spring-core = { module = "org.springframework:spring-core", version.ref = "spring" }
spring-context = { module = "org.springframework:spring-context", version.ref = "spring" }
springboot-starter-core = { module = "org.springframework.boot:spring-boot-starter", version.ref = "springboot" }
springboot-starter-autoconfigure = { module = "org.springframework.boot:spring-boot-autoconfigure", version.ref = "springboot" }
springboot-starter-log4j2 = { module = "org.springframework.boot:spring-boot-starter-log4j2", version.ref = "springboot" }
springboot-test = { module = "org.springframework.boot:spring-boot-test", version.ref = "springboot" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
testcontainers-core = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers"}
testcontainers-spock = { module = "org.testcontainers:testcontainers-spock", version.ref = "testcontainers"}
testcontainers-postgresql = { module = "org.testcontainers:testcontainers-postgresql", version.ref = "testcontainers"}
project-reactor-core = { module = "io.projectreactor:reactor-core", version.ref = "project-reactor" }
r2dbc-spi = { module ='io.r2dbc:r2dbc-spi', version.ref = "r2dbc"}
r2dbc-pool = { module = 'io.r2dbc:r2dbc-pool', version.ref = "r2dbc-pool"}
r2dbc-postgresql = { module = 'org.postgresql:r2dbc-postgresql', version.ref = "r2dbc-postgresql"}
jdbc-postgres = { module = 'org.postgresql:postgresql', version.ref = "jdbc-postgres"}
flyway-core = { module = 'org.flywaydb:flyway-core', version.ref = "flyway"}
flyway-postgresql = { module = 'org.flywaydb:flyway-database-postgresql', version.ref = "flyway"}
jackson-core = { module = "tools.jackson.core:jackson-core", version.ref = "jackson" }
jackson-databind = { module = "tools.jackson.core:jackson-databind", version.ref = "jackson" }
netty-handler = { module = "io.netty:netty-handler", version.ref = "netty" }
netty-common = { module = "io.netty:netty-common", version.ref = "netty" }
netty-transport = { module = "io.netty:netty-transport", version.ref = "netty" }
netty-codec = { module = "io.netty:netty-codec", version.ref = "netty" }
netty-codechttp = { module = "io.netty:netty-codec-http", version.ref = "netty" }

legacy-jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "legacy-jackson" }

jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

spring-r2dbc = { module = "org.springframework:spring-r2dbc", version.ref = "spring" }
spring-test = { module = "org.springframework:spring-test", version.ref = "spring" }
spock-core = { module = "org.spockframework:spock-core", version.ref = "spock" }
spock-spring = { module = "org.spockframework:spock-spring", version.ref = "spock" }
groovy-core = { module = "org.apache.groovy:groovy", version.ref = "groovy" }
groovy-all = { module = "org.apache.groovy:groovy-all", version.ref = "groovy" }
byte-buddy-dep = { module = "net.bytebuddy:byte-buddy-dep", version.ref = "byte-buddy" }
objenesis = { module = "org.objenesis:objenesis", version.ref = "objenesis" }
hivemq-mqtt-client = { module = "com.hivemq:hivemq-mqtt-client", version.ref = "hivemq-mqtt-client" }
moquette-broker = { module = "io.moquette:moquette-broker", version.ref = "moquette-broker" }

[bundles]
netty-bundle = ["netty-handler", "netty-common", "netty-transport", "netty-codec", "netty-codechttp"]
