plugins {
  id("java-library")
  id("configure-java")
  id("groovy")
}

configurations.all {
  resolutionStrategy {
    force "commons-beanutils:commons-beanutils:1.11.0"
    force "commons-codec:commons-codec:1.20.0"
  }
}

dependencies {
  api projects.network
  implementation "com.bertramlabs.plugins:hcl4j:0.9.8"

  testImplementation projects.testSupport
  testImplementation libs.rlib.logger.impl
  testImplementation testFixtures(projects.network)
}