plugins {
  id("java-library")
  id("configure-java")
  id("groovy")
}

description = "Implementation of network layer for MQTT Protocol"

dependencies {
  api projects.model
  api libs.project.reactor.core
  api libs.rlib.network
  api libs.rlib.logger.api

  testImplementation projects.testSupport
  testImplementation libs.rlib.logger.impl
  testFixturesApi projects.testSupport
}
