plugins {
  id("java-library")
  id("configure-java")
  id("groovy")
}

description = "Database-based Credentials Source Provider"

dependencies {
  api projects.base
  api projects.authenticationBasic
  api libs.r2dbc.spi
  api libs.r2dbc.pool
  api libs.r2dbc.postgresql

  testImplementation projects.testSupport
  testFixturesApi projects.testSupport
}
