plugins {
  id("configure-java")
  id("jacoco-report-aggregation")
}

description = "Aggreggate test coverages from all modules"

dependencies {
  jacocoAggregation projects.base
  jacocoAggregation projects.application
  jacocoAggregation projects.model
  jacocoAggregation projects.network
  jacocoAggregation projects.coreService
}
