plugins {
  id("configure-java")
  id("jacoco-report-aggregation")
}

description = "Aggregate test coverages from all modules"

dependencies {
  jacocoAggregation projects.base
  jacocoAggregation projects.application
  jacocoAggregation projects.model
  jacocoAggregation projects.network
  jacocoAggregation projects.coreService
  jacocoAggregation projects.aclEngine
  jacocoAggregation projects.aclGroovyDsl
  jacocoAggregation projects.aclService
  jacocoAggregation projects.aclAntlrDsl
}
